config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  
  resources :chatareas do
    resource :chatarea_users
    resources :messages do
      get "/ping" => "messages#ping"
    end
    post "/prank" => "chatareas#prank"
  end

  namespace :admin do
      resources :users

      root to: "users#index"
  end
  
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users
  root to: 'chatareas#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/chatarea.rb
class Chatarea < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: [:slugged, :finders]

    has_many :chatarea_users, dependent: :destroy
    has_many :users, through: :chatarea_users, dependent: :destroy
    has_many :messages, dependent: :destroy

    def short_display_message
        message = self.messages.where(is_auto: false).last
        return "<b>#{message.user.name}</b>: #{message.body[0..20]+"..."}" unless message.nil?
        "No conversation made"
    end

    def auto_reply_and_notifiy_offline_user(user, message)
        self.messages.create(user_id: user.id, body: "Users are currently offline", is_auto: true)
        to_user_ids = self.chatarea_users.pluck(:user_id) - [message.user.id]
        NotificationRelayJob.perform_later(to_user_ids, message.user.name, message.chatarea.name, message.short_message)
    end

    def user_joined?(user_id)
        self.chatarea_users.pluck(:user_id).include? user_id
    end
end

app/controllers/chatareas_controller.rb
class ChatareasController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_chatarea, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_chatarea_user!, except: [:index]

  # GET /chatareas
  # GET /chatareas.json
  def index
    @chatareas = Chatarea.includes(:chatarea_users)
    @common_words = Message.common_words
  end

  # GET /chatareas/1
  # GET /chatareas/1.json
  def show
    @messages = @chatarea.messages.order(created_at: :desc).limit(100).reverse
  end

  # GET /chatareas/new
  def new
    @chatarea = Chatarea.new
  end

  # GET /chatareas/1/edit
  def edit
  end

  # POST /chatareas
  # POST /chatareas.json
  def create
    @chatarea = current_user.chatareas.new(chatarea_params)

    respond_to do |format|
      if @chatarea.save
        @chatarea.chatarea_users.where(user_id: current_user.id).first_or_create
        format.html { redirect_to chatareas_path, notice: 'Chatarea was successfully created.' }
        format.json { render :show, status: :created, location: @chatarea }
      else
        format.html { render :new }
        format.json { render json: @chatarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatareas/1
  # PATCH/PUT /chatareas/1.json
  def update
    respond_to do |format|
      if @chatarea.update(chatarea_params)
        format.html { redirect_to @chatarea, notice: 'Chatarea was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatarea }
      else
        format.html { render :edit }
        format.json { render json: @chatarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatareas/1
  # DELETE /chatareas/1.json
  def destroy
    @chatarea.destroy
    respond_to do |format|
      format.html { redirect_to chatareas_url, notice: 'Chatarea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def prank
    @chatarea = Chatarea.find(params[:chatarea_id])
    1.upto(1000).each do |time|
      @chatarea.messages.create(user_id: current_user.id, body: "Woahh! This is fun...", is_auto: true)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatarea
      @chatarea = Chatarea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chatarea_params
      params.require(:chatarea).permit(:name, :user_limit)
    end

    def authenticate_chatarea_user!
      chatarea_id = params[:id] || params[:chatarea_id]
      @chatarea = Chatarea.find(chatarea_id) if @chatarea.nil?
      redirect_to root_path if @chatarea.chatarea_users.find_by(user_id: current_user.id).nil?
    end
end

app/helpers/chatareas_helper.rb
module ChatareasHelper
end

app/views/chatareas/_form.html.erb
<%= form_with(model: chatarea, local: true) do |form| %>
  <% if chatarea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chatarea.errors.count, "error") %> prohibited this chatarea from being saved:</h2>

      <ul>
      <% chatarea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :user_limit %>
    <%= form.text_field :user_limit, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if chatarea.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', chatarea, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if chatarea.persisted? %>
      <%= link_to "Cancel", chatarea, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", chatareas_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/chatareas/edit.html.erb
<h1>Edit Chatarea</h1>

<%= render 'form', chatarea: @chatarea %>

app/views/chatareas/index.html.erb
<% unless @common_words.empty? %>
  <h5>Commonly used words in recent times</h5>
  <div class="my-4 d-flex flex-row">
    <% @common_words.each do |word| %>
      <small class="tag"><%= word %></small>
    <% end %>
  </div>
  <hr />
<% end %>
<div class="mt-4 table-responsive" style="overflow-y: auto;">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Users</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @chatareas.each do |chatarea| %>
        <%= content_tag :tr, id: dom_id(chatarea), class: dom_class(chatarea) do %>
            <td><%= chatarea.name %></td>
            <td><%= "#{chatarea.chatarea_users.count} of #{chatarea.user_limit}" %></td>
            <% if current_user %>
              <% if chatarea.user_joined? current_user.id %>
                <td><%= link_to "View", chatarea_path(chatarea) %></td>
              <% else %>
                <td><%= button_to "Join", chatarea_chatarea_users_path(chatarea) %></td>
              <% end %>
            <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/chatareas/index.js.erb
if(Notification.permission === 'granted') {
    let title = "Push Notification test";
    let body = "Life is all about new findings"
    let options = {body: body}

    new Notification(title, options)
}

app/views/chatareas/new.html.erb
<h1>New chatarea</h1>

<%= render 'form', chatarea: @chatarea %>

app/views/chatareas/show.html.erb
<div class="chat-section">
  <div class="row">
    <div class="col-11 pt-1 pb-2 border-bottom">
      <h4 class="mb-0"><%= @chatarea.name %></h4>
      <h6 class="mb-0 small"><%= truncate(@chatarea.chatarea_users.names, length: 100) %></h6>
    </div>
    <div class="col-1 align-items-center pt-1 pb-2 border-bottom">
      <%= link_to "prank", chatarea_prank_path(@chatarea.id), class: "btn btn-warning btn-sm", method: :post, remotre: true%>
    </div>
  </div>

  <div id="chat-area-section" class="row chat-area mb-4">
    <div class="container-fluid mt-2 mb-2">
      <div data-user-id="<%= current_user.id %>" data-behaviour="messages" data-chatarea-id="<%= @chatarea.id %>">
        <% @messages.each do |message| %>
          <%= render message %>
        <% end %>
      </div>
    </div>
  </div>

  <%= form_for [@chatarea, Message.new], remote: true, authenticity_token: true, format: "js" do |f| %>
    <div class="row chat-compose border-top pb-1">
      <%= f.text_field :body, class: "col-8 col-md-10 form-control border-0", autofocus: true, autocomplete: "off", placeholder: "Type your message..." %>
      <div class="col-4 col-md-2 p-2">
        <%= f.submit "Send", class: "btn btn-outline-primary btn-block", id: "new_message_submit_btn" %>
      </div>
    </div>
  <%end%>
</div>