config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  
  resources :chatareas do
    resource :chatarea_users
    resources :messages do
      get "/ping" => "messages#ping"
    end
    post "/prank" => "chatareas#prank"
  end

  namespace :admin do
      resources :users

      root to: "users#index"
  end
  
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users
  root to: 'chatareas#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer class="footer text-muted bg-light">
  <div class="container">
    <span>© <%= Date.today.year %> Your Company</span>
  </div>
</footer>

app/views/shared/_head.html.erb
<title><%= Rails.configuration.application_name %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/shared/_navbar.html.erb
<% if user_masquerade? %>
  <div class="alert alert-warning text-center">
    You're logged in as <b><%= current_user.name %> (<%= current_user.email %>)</b>
    <%= link_to back_masquerade_path(current_user) do %><%= icon("fas", "times") %> Logout <% end %>
  </div>
<% end %>

<header class="navbar navbar-expand-lg navbar-dark bg-primary">
    <%= link_to Rails.configuration.application_name, root_path, class: "navbar-brand" %>

    <div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#chat-nav" aria-controls="chat-nav"
        aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa fa-bars p-1"></i>
      </button>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarMain"
          aria-expanded="false" aria-label="Toggle navigation">
          <i class="fa fa-ellipsis-v p-1"></i>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      </ul>

      <ul id="login-nav" class="navbar-nav text-right">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
              Hi, <%= current_user.first_name %> <%= image_tag gravatar_image_url(current_user.email, size: 40), height: 20, width: 20, class: "ml-2 rounded" %>
            <% end %>
            <div id="nav-account-dropdown" class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-dropdown">
              <% if current_user.admin? %>
                <%= link_to "Admin Area", admin_root_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
</header>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %>">
    <div class="container">
      <button class="close" data-dismiss="alert"><span>×</span></button>
      <%= message %>
    </div>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<nav class="chat-links pt-4 pt-md-0 pb-4 pb-md-0" id="chat-nav">
    <% if user_signed_in? %>
        <div class="row">
            <div class="col-8">
                <h4>Subscriptions</h4>
            </div>
            <div class="col-4 text-right">
                <%= link_to "Create", new_chatarea_path, class: "btn btn-primary btn-sm text-white" %>
            </div>
        </div>
        <ul class="list-group mt-3">
            <% current_user.chatareas.each do |chatarea| %>
                    <li class="d-flex justify-content-between align-items-center conversation-list-item" data-behaviour="chatarea-link" data-chatarea-id="<%= chatarea.id %>">
                        <%= link_to chatarea_path(chatarea), class: "w-100" do %>
                            <div class="conversation-list-initial <%= profile_badge_helper(chatarea.name[0].upcase) %> mr-2"><%= chatarea.name[0].upcase %></div>
                            <div class="conversation-list-info">
                                <h5 class="mb-0"><%= chatarea.name %></h5>
                                <small id="conversation-short-message-<%= chatarea.id %>"><%= sanitize chatarea.short_display_message %></small>
                            </div>
                        <% end %>
                        <div id="chat-area-list-actions">
                            <%= link_to chatarea_chatarea_users_path(chatarea), method: :delete do %>
                                <i class="fa text-danger fa-trash fa-xs"></i>
                            <% end %>
                        </div>
                    </li>
            <% end %>
        </ul>
    <% end %>
</nav>